"""Initial schema: products, supermarkets, prices

Revision ID: aa91ec3623ad
Revises:
Create Date: 2025-11-20 18:38:56.052641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa91ec3623ad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_products_name"),  # Unique constraint on product name
    )
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_table(
        "supermarkets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_supermarkets_city"), "supermarkets", ["city"], unique=False)
    op.create_index(op.f("ix_supermarkets_id"), "supermarkets", ["id"], unique=False)
    op.create_index(op.f("ix_supermarkets_name"), "supermarkets", ["name"], unique=False)
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["supermarkets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "store_id", name="uq_prices_product_store"
        ),  # Unique constraint
        sa.CheckConstraint("price >= 0.01", name="chk_prices_price_positive"),  # Check constraint
    )
    op.create_index("idx_price_product_store", "prices", ["product_id", "store_id"], unique=False)
    op.create_index(op.f("ix_prices_id"), "prices", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prices_id"), table_name="prices")
    op.drop_index("idx_price_product_store", table_name="prices")
    op.drop_table("prices")
    op.drop_index(op.f("ix_supermarkets_name"), table_name="supermarkets")
    op.drop_index(op.f("ix_supermarkets_id"), table_name="supermarkets")
    op.drop_index(op.f("ix_supermarkets_city"), table_name="supermarkets")
    op.drop_table("supermarkets")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
